name: PreMerge Build

on:
  pull_request:
    branches:
      - main  # PRのターゲットブランチがmainの場合に動作する

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: cd front && npm install

      - name: Build the project
        run: npm run build
